SELECT VAL, COUNT(VAL) AS FREQ 
FROM SOLICITUDES_VAL 
GROUP BY VAL ORDER BY COUNT(VAL) ASC;

SELECT ACTIVE_LOGIN, COUNT(ACTIVE_LOGIN) AS FREQ 
FROM SOLICITUDES 
GROUP BY ACTIVE_LOGIN ORDER BY COUNT(ACTIVE_LOGIN) ASC;

SELECT USER_LOGIN AS PASSIVE_LOGIN, FREQ
FROM
	(
		SELECT PASSIVE_REGISTER, COUNT(PASSIVE_REGISTER) AS FREQ 
		FROM ACTIVESPASSIVES 
		GROUP BY PASSIVE_REGISTER ORDER BY COUNT(PASSIVE_REGISTER) ASC
	) 
REGISTERS INNER JOIN PASSIVES
ON REGISTERS.PASSIVE_REGISTER = PASSIVES.PASSIVE_REGISTER;

SELECT PK_VAL, COUNT(PK_VAL) AS FREQ 
FROM PORTFOLIOS_VALS 
GROUP BY PK_VAL ORDER BY COUNT(PK_VAL) ASC;

SELECT COUNT(*)
FROM SOLICITUDES_VAL;